import express from 'express';
import cors from 'cors';
import puppeteer from 'puppeteer';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express(); app.use(cors()); app.use(express.json({ limit: '4mb' }));
const receiptCss = await fs.readFile(path.join(__dirname, '../src/components/receipt/receipt.css'), 'utf8');
const logoData = `data:image/png;base64,${(await fs.readFile(path.join(__dirname, '../public/assets/mr-transmission-logo.png'))).toString('base64')}`;
const renderer = ({receipt,settings}) => { const money=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}); const subtotal=(receipt.items||[]).reduce((s,i)=>s+Number(i.total||0),0); const discount=Number(receipt.discount||0); const tax=Math.max(subtotal-discount,0)*Number(receipt.tax_rate??settings.tax_rate??0)/100; const total=subtotal-discount+tax; const c=receipt.customer||{},v=receipt.vehicle||{}; return `<!doctype html><html><head><meta charset="utf-8"><style>${receiptCss}body{margin:0;background:#fff}.receipt-page{margin:0}</style></head><body><div class="receipt-page"><header class="receipt-header"><h1>PAYMENT RECEIPT</h1><img class="receipt-logo" src="${logoData}"><div class="company-lines"><div>${settings.address||''}</div><div>PHONE : ${settings.phone||''} * FAX: ${settings.fax||''}</div><div>${settings.email||''}</div></div></header><section class="receipt-meta"><div class="customer-meta"><div><b>RECEIPT NO:</b> ${receipt.receipt_no||''}</div><div><b>BILLED TO:</b> ${c.name||''}</div><div><b>ADDRESS:</b> ${c.address||''}</div><div class="spacer"></div><div><b>PHONE NUMBER :</b> ${c.phone||''}</div><div><b>E-MAIL:</b> ${c.email||''}</div><div><b>PLATE NUMBER:</b> ${v.plate_number||''}</div><div><b>VIN:</b> ${v.vin||''}</div></div><div class="vehicle-meta"><div><b>ARRIVE:</b> ${receipt.arrive_date||''}</div><div><b>YEAR:</b> ${v.year||''}</div><div><b>MAKE:</b> ${v.make||''}</div><div><b>MODEL:</b> ${v.model||''}</div><div><b>COLOR:</b> ${v.color||''}</div><div><b>MILEAGE IN:</b> ${v.mileage_in||''}</div><div><b>MILEAGE OUT:</b> ${v.mileage_out||''}</div><div><b>ENGINE SIZE:</b> ${v.engine_size||''}</div></div></section>${receipt.show_vehicle_details&&receipt.vehicle_details?`<section class="receipt-details"><b>VEHICLE DETAILS:</b><div>${receipt.vehicle_details}</div></section>`:''}<table class="receipt-items"><colgroup><col/><col class="qty-col"/><col class="total-col"/></colgroup><thead><tr><th>DESCRIPTION</th><th>QTY</th><th>TOTAL</th></tr></thead><tbody>${(receipt.items||[]).map(i=>`<tr><td>${i.description||''}</td><td>${i.qty||''}</td><td>${money(i.total)}</td></tr>`).join('')}</tbody></table><div class="receipt-lower"><div class="guarantee-notes"><div class="guarantee"><b>GUARANTEE:</b><div>${receipt.guarantee||''}</div></div><div class="notes"><b>NOTES:</b><div>${receipt.notes||''}</div></div></div><div class="totals"><div class="rule"></div><div><span>SUB-TOTAL:</span><strong>${money(subtotal)}</strong></div><div><span>DISCOUNT:</span><strong>-${money(discount)}</strong></div><div><span>TAX:</span><strong>${money(tax)}</strong></div><div class="final"><span>TOTAL:</span><strong>$${money(total)}</strong></div><div class="after"><span>TOTAL AFTER<br>DISCOUNT:</span><strong>$${money(subtotal-discount)}</strong></div><div class="signature">SIGNATURE</div></div></div></div></body></html>`; };
app.post('/api/pdf', async (req,res)=>{let browser;try{browser=await puppeteer.launch({headless:'new',args:['--no-sandbox','--disable-setuid-sandbox']});const page=await browser.newPage();await page.setViewport({width:794,height:1123,deviceScaleFactor:1});await page.setContent(renderer(req.body),{waitUntil:'networkidle0'});const pdf=await page.pdf({format:'A4',printBackground:true,margin:{top:0,right:0,bottom:0,left:0}});res.set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="receipt-${req.body.receipt?.receipt_no||'receipt'}.pdf"`}).send(pdf)}catch(e){res.status(500).json({error:e.message})}finally{if(browser)await browser.close()}});
app.listen(process.env.PORT||8787,()=>console.log('PDF server listening on http://localhost:8787'));
